defaults:
  - _self_
  - aml_config
  - aoai_config

zeroshot_config:
  pipeline:
    base_experiment_name: gsm8k_zeroshot_debugging
    tags:
    default_compute_target: isolatedcompute
  json_guidance_programs:
    - gsm8k_zero_or_few_shot.py
  transformer_config:
    compute_target: gput4