defaults:
  - _self_
  - aml_config
  - aoai_config

zeroshot_config:
  pipeline:
    base_experiment_name: zeroshot
    tags:
    default_compute_target: isolatedcompute
  mmlu_dataset: clinical_knowledge
  mmlu_split: test
  max_errors: 10
  guidance_workers: 10
  guidance_program: zero_shot.py
  aoai_config: ${ default_aoai_config }