defaults:
  - _self_
  - aml_config

zeroshot_config:
  base_experiment_name: zeroshot
  tags:
  mmlu_dataset: anatomy
  mmlu_split: test
  default_compute_target: <Regular compute>
  guidance_program: zero_shot.py
  aoai_config:
    endpoint: <ENDPOINT>
    model: <MODEL>
    compute_target: <compute authorised for endpoint>